These are all of the URLs that the algorithm wrongly classified as not phishingLinks 

URL: https://0r26fj1wp2hvqapn3w.sept11mn.org/?_rdr
Points: 50

The website generated the following report:
		The URL violated the following special characters: ['0', '3', '1']
		The URL had a phishy length with 29 letters

	www: None
	protocol: https
	subDomain: 0r26fj1wp2hvqapn3w
	domain: sept11mn
	topDomain: org
	dir: None
	file: None
	path: /
	fragment: None
	query: {'_rdr': None}
	ip: None
	city: None
	country: None
	region: None
	favicon: None
	expires: None
	registered: None
	update: None
	active: None

Error during DNS resolving: [Errno 11001] getaddrinfo failed
Error during HTML info collecting: HTTPSConnectionPool(host='0r26fj1wp2hvqapn3w.sept11mn.org', port=443): Max retries exceeded with url: /?_rdr (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5F96A4760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
------------------------

URL: http://4afic.mylp.kz
Points: 20

The website generated the following report:
		The website is using HTTP

	www: None
	protocol: http
	subDomain: 4afic
	domain: mylp
	topDomain: kz
	dir: None
	file: None
	path: None
	fragment: None
	query: None
	ip: None
	city: None
	country: None
	region: None
	favicon: None
	expires: None
	registered: None
	update: None
	active: None

Error during DNS resolving: [Errno 11001] getaddrinfo failed
Error during HTML info collecting: HTTPConnectionPool(host='4afic.mylp.kz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F96A4D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
------------------------

The accuracy was: 33%
